project/notafiscal/urls.py
from django.urls import path


from . import views as v


app_name = 'notafiscal'


urlpatterns = [
    # path('', TemplateView.as_view(template_name="notafiscal/uploadxml.html")),
    path('lista/', v.nfcompraList, name='nfcompraList'),
    path('lista/baixar/', v.notafiscalList, name='notafiscalList'),
    path('baixar/<chave>/', v.checkXml, name='checkXml'),
    path('baixar/xml/', v.baixarxml, name='baixarxml'),
    path('<int:pk>/deletar/', v.nfcompraDelete, name='nfcompraDelete'),
]

project/project/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


from django.views.generic.base import TemplateView

# from .views import index

urlpatterns = [
    path("", TemplateView.as_view(template_name="account/login.html")),
    path("admin/", admin.site.urls),
    path(
        "index/",
        login_required(TemplateView.as_view(template_name="index.html")),
        name="index",
    ),
    path("accounts/", include("allauth.urls")),
    path("select2/", include("django_select2.urls")),
    path("compra/", include("compra.urls"), name="compra"),
    path("venda/", include("venda.urls"), name="venda"),
    path("mercadolivre/", include("mercadolivre.urls"), name="mercadolivre"),
    path("cliente/", include("cliente.urls"), name="cliente"),
    path("notafiscal/", include("notafiscal.urls"), name="notafiscal"),
    path("estoque/", include("estoque.urls"), name="estoque"),
    path("financeiro/", include("financeiro.urls"), name="financeiro"),
    path("despesa/", include("despesa.urls"), name="despesa"),
    path("receita/", include("receita.urls"), name="receita"),
    path("materiaprima/", include("materiaprima.urls"), name="materiaprima"),
    path("producao/", include("producao.urls"), name="producao"),
    path("transporte/", include("transportadora.urls"), name="transportadora"),
    path("expedicao/", include("expedicao.urls"), name="expedicao"),
    path("fornecedor/", include("fornecedor.urls"), name="fornecedor"),
    path("produto/", include("produto.urls"), name="produto"),
    path("suporte/", include("suporte.urls"), name="suporte"),
    path("representante/", include("representante.urls"), name="representante"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/venda/urls.py
from django.urls import path

from . import views as v


app_name = "venda"


urlpatterns = [
    path("", v.vendaList, name="vendaList"),
    path("ajax/", v.getVendasAjax, name="getVendasAjax"),
    path("relatorios/", v.relatorios, name="relatorios"),
    path("ano/", v.total_vendido_ano, name="total_vendido_ano"),
    path("mes/", v.total_vendido_mes, name="total_vendido_mes"),
    path("select/meses/", v.meses_ajax, name="meses_ajax"),
    # path("select/anos/", v.anos_ajax, name="anos_ajax"),
    path("cadastrar/", v.vendaCreate, name="vendaCreate"),
    path("cadastrar/preco/", v.produtoPrecoAjax, name="produtoPrecoAjax"),
    path("cadastrar/cliente/", v.clienteAjax, name="clienteAjax"),
    path("cadastrar/condicoes/parcelas/", v.condicaoAjax, name="condicaoAjax"),
    path("boletos/", v.boletoList, name="boletoList"),
    path("<hash>/orcamento/<int:id>/", v.orcamento, name="orcamento"),
    path("<int:pk>/editar/", v.vendaUpdate, name="vendaUpdate"),
    path("<int:pk>/clonevenda/", v.vendaClone, name="vendaClone"),
    path("<int:pk>/deletar/", v.vendaDelete, name="vendaDelete"),
    path("<int:pk>/nf/", v.vendaNF, name="vendaNF"),
    path("<int:pk>/expedicao/", v.expedicaoNF, name="expedicaoNF"),
    path(
        "<transportadora>/check/transporte/",
        v.listaConferenciaTransporteExpedicao,
        name="listaConferenciaTransporteExpedicao",
    ),
    path("<venda>/<cotacao>/deletar/cotacao/", v.deletarCotacao, name="deletarCotacao"),
]

project/notafiscal/forms.py
from django import forms

from .models import NFCompra, NFItem


class NFCompraForm(forms.ModelForm):
    template_name_crete_update = "notafiscal/notafiscalCreateUpdate.html"

    class Meta:
        model = NFCompra
        fields = "__all__"
        widgets = {
            "fornecedor": forms.Select(
                attrs={
                    "class": "form-control form-control-sm border-0 bg-white p-0",
                    "readonly": "readonly",
                }
            ),
            "chavedeacesso": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "naturezadaoperacao": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "numeroserie": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "protocoloautorizacaodeuso": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "nome_destinatario": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "cnpj_destinatario": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "bairro_destinatario": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "cep_destinatario": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "data_emissao": forms.DateInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "forma_pagamento": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "base_calculo_icms": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_icms": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_pis": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_total_produtos": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_do_frete": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_do_seguro": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "desconto": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "outras_despesas": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_total_ipi": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_da_cofins": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_total_da_nota": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
        }


class NFCompraProdutoForm(forms.ModelForm):
    class Meta:
        model = NFItem
        fields = [
            "codigo_produto",
            "materiaprima",
            "un",
            "valor_unitario",
            "quantidade",
            "ncm_sh",
            "cfop",
            "valor_total",
            "valor_icms",
            "valor_ipi",
        ]
        labels = {
            "codigo_produto": "",
            "materiaprima": "",
            "un": "",
            "valor_unitario": "",
            "quantidade": "",
            "ncm_sh": "",
            "cfop": "",
            "valor_total": "",
            "valor_icms": "",
            "valor_ipi": "",
        }
        widgets = {
            "materiaprima": forms.Select(
                attrs={"class": "form-control form-control-sm", "required": "required"}
            ),
            "codigo_produto": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "materiaprima": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "un": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_unitario": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "quantidade": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "ncm_sh": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "cfop": forms.TextInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_total": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            # 'o_csqn': forms.TextInput(attrs={'class': 'form-control form-control-sm border-0 p-0','readonly':'readonly'}),
            # 'valor_desconto': forms.NumberInput(attrs={'class': 'form-control form-control-sm border-0 p-0','readonly':'readonly'}),
            # 'b_calc_imcs': forms.TextInput(attrs={'class': 'form-control form-control-sm border-0 p-0','readonly':'readonly'}),
            "valor_icms": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            "valor_ipi": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm border-0 p-0",
                    "readonly": "readonly",
                }
            ),
            # 'aliq_icms': forms.TextInput(attrs={'class': 'form-control form-control-sm border-0 p-0','readonly':'readonly'}),
            # 'aliq_ipi': forms.TextInput(attrs={'class': 'form-control form-control-sm border-0 p-0','readonly':'readonly'}),
        }

        # def __init__(self, *args, **kwargs):
        #     super(NFCompraForm, self).__init__(*args, **kwargs)
        #     self.fields['codigo_produto'].widget.attrs['readonly'] = True
        #     self.fields['materiaprima'].widget.attrs['readonly'] = True
        #     self.fields['un'].widget.attrs['readonly'] = True
        #     self.fields['valor_unitario'].widget.attrs['readonly'] = True
        #     self.fields['quantidade'].widget.attrs['readonly'] = True
        #     self.fields['ncm_sh'].widget.attrs['readonly'] = True
        #     self.fields['cfop'].widget.attrs['readonly'] = True
        #     self.fields['valor_total'].widget.attrs['readonly'] = True
        # self.fields['o_csqn'].widget.attrs['readonly'] = True
        # self.fields['valor_desconto'].widget.attrs['readonly'] = True
        # self.fields['b_calc_imcs'].widget.attrs['readonly'] = True
        # self.fields['valor_icms'].widget.attrs['readonly'] = True
        # self.fields['valor_ipi'].widget.attrs['readonly'] = True
        # self.fields['aliq_icms'].widget.attrs['readonly'] = True

project/notafiscal/templates/notafiscal/nfcompraDelete.html
{% extends 'index.html' %}

{% load static %}

<title> {% block title %} Delete Nota Fiscal {% endblock title%} </title>


{% block index %}

<div class="container">
    <h5>Delete</h5>
    <div class="cols-6">
        <form action="." method="POST">
            <div class="col-sm-6">
                {% csrf_token %}
                <p>Você tem certeza que deseja deletar o registro: <b>{{ object.fornecedor }}, CNPJ:
                        {{ object.cnpj_destinatario }}, emitido em {{ object.data_emissao|date:"d/m/Y" }}</b>?</p>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-sm">Confirmar</button>
                    <a class="btn btn-secondary btn-sm" href="{% url 'notafiscal:nfcompraList' %}">Cancelar</a>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

project/notafiscal/templates/notafiscal/nfcompraDetails.html
{% extends 'index.html' %}

{% load static %}

<title> {% block title %} Detalhes da Nota Fiscal {% endblock title%} </title>


{% block index %}
<div class="container">
    <div class="invoice bg-white rounded-3">
        <div class="row d-flex justify-content-between px-0 p-lg-4">
            <div class="col-12 col-md-8 mb-3">
                <div class="d-flex">
                    <img src="{% static 'img/logo.png' %}" width="30" height="30">
                    <h6 class="m-0 ps-2 fs-5 text-dark text-uppercase">Original</h6>
                </div>
                <div class="mt-4 p-0">
                    <p class="fw-bold ">Emitente</p>
                    {% for fornec in fornec %}
                    <b>{{ fornec.nome }}</b>
                    <p class="m-0">{{ fornec.logradouro }}, {{ fornec.numero }} {{ fornec.complemento }}</p>
                    <p class="m-0">{{ fornec.cidade }}, {{ fornec.estado }} {{ fornec.cep }}</p>
                    <p class="m-0">{{ fornec.telefone1|default:"" }} {{fornec.telefone2|default:"" }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-7 col-md-4 mb-2" align="right">
                <div class="d-flex justify-content-center pb-1" align="left">
                    <h6 class="col-6 col-md-5 fs-5 text-dark">Nota Fiscal</h6>
                    <h6 class="col-6 col-md-5 fs-5 fw-bold text-dark">{{ num_nf }}</h6>
                </div>
                <div class="d-flex justify-content-center py-0" align="left">
                    <p class="col-6 col-md-5">Date da Emissão: </p>
                    <p class="col-6 col-md-5 fw-bold">{{ data_emissao }}</p>
                </div>
                <div class="d-flex justify-content-center pt-0" align="left">
                    <p class="col-6 col-md-5"></p>
                    <p class="col-6 col-md-5 fw-bold"></p>
                </div>
            </div>
        </div>
        <hr class="my-0">
        <div class="row d-flex justify-content-between px-0 p-lg-4">
            <div class="col-12 col-md-6">
                {% for d in dest %}
                <p class="fw-bold ">Recebedor</p>
                <div class="row align-items-center p-0">
                    <p class="col-8 col-md-8">{{ d.xNome }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col-9 col-md-8 m-0">CNPJ {{ d.CNPJ }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col-9 col-md-8 m-0">{{ d.xLgr }}, {{ d.nro }}, {{ d.xBairro }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col-9 col-md-8 m-0">{{ d.xMun }}, {{ d.UF }}</p>
                </div>
                {% endfor %}
            </div>
            {% for destinatario in dest %}
            <div class="col-12 col-md-5">
                <div class="row align-items-center p-0">
                    <p class="col-2 m-0">
                        Total: </p>
                    <p class="col-10 m-0">{{ destinatario.total }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col-2 m-0">
                        NatOp:</p>
                    <p class="col-10 m-0">{{ destinatario.natop }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col-2 m-0">
                        Série:</p>
                    <p class="col-10 m-0">{{ destinatario.serie }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col-2 m-0">
                        Chave:</p>
                    <p class="col-12 col-lg-10 m-0">{{ destinatario.chave }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col-2 m-0">
                        AutUso:</p>
                    <p class="col-10 m-0">{{ destinatario.autuso }}</p>
                </div>
            </div>
        </div>
        <hr class="m-0">
        <div class="px-lg-3">
            <table class="table table-sm" id="id_table">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Produto</th>
                        <th>UniMed</th>
                        <th>Valor(R$)</th>
                        <th>Quant</th>
                        <th>NCM</th>
                    </tr>
                </thead>
                <tbody>
                    {% for prod in items %}
                    <tr>
                        <td>{{ prod.codigo_produto }}</td>
                        <td>{{ prod.materiaprima }}</td>
                        <td>{{ prod.un }}</td>
                        <td>{{ prod.valor_unitario }}</td>
                        <td>{{ prod.quantidade }}</td>
                        <td>{{ prod.ncm }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row d-flex justify-content-between mx-1 px-3">
            <div class="col-12 col-md-6 d-none d-md-block">
                <div class="row align-items-center p-0">
                    <p class="col">Forma de Pagamento:</p>
                    <p class="col">{{ destinatario.forpgto }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col">Base cálculo ICMS:</p>
                    <p class="col">{{ destinatario.bcicms }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col">ICMS</p>
                    <p class="col">{{ destinatario.vlricms }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col">Valor do PIS:</p>
                    <p class="col">{{ destinatario.vlrpis }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col">Valor do Frete:</p>
                    <p class="col">{{ destinatario.vlrfrete }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col">Valor do Seguro:</p>
                    <p class="col">{{ destinatario.vlrseguro }}</p>
                </div>
            </div>
            <div class="col-12 col-md-4 justify-content-end p-0 ">
                <div class="row align-items-center p-0">
                    <p class="col">Subtotal:</p>
                    <p class="col">{{ destinatario.subtotal }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col">Desconto:</p>
                    <p class="col">{{ destinatario.desconto }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col">Outras despesas:</p>
                    <p class="col">{{ destinatario.odespesas }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col">Valor Total IPI</p>
                    <p class="col">{{ destinatario.vlripi }}</p>
                </div>
                <div class="row align-items-center p-0">
                    <p class="col">Valor da COFINS:</p>
                    <p class="col">{{ destinatario.vlrcofins }}</p>
                </div>
                <hr class="my-2">
                <div class="row align-items-center p-0">
                    <p class="col">total:</p>
                    <p class="col">{{ destinatario.total }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-12 d-flex gap-2 justify-content-end pe-3 pb-3">
            <a role="button" class="btn btn-primary btn-sm" href="{% url 'notafiscal:nfcompraList' %}">Sair</a>
        </div>
        <hr class="my-1">
        <div class="row d-flex mx-1 px-3">
            <p class="text-left p-0"><strong>Note:</strong> </p>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Cadastrar Produtos</h5>
            </div>
            <div class="modal-body">
                Selecione um Nome para cada Produto
                <form method="POST">
                    {% csrf_token %}
                    {{ formset.management_form }}
                    {{ formset.non_form_errors }}
                    {% for form in formset %}
                    <div class="card mb-2 p-2">
                        <div class="row gap-2">
                            <div class="col-12">{{ form.materiaprima }}</div>
                            <div class="col-12">{{ form.fornecedor }}
                            </div>
                            <div class="row">
                                <div class="col-4">{{ form.codigoproduto }}</div>
                                <div class="col-8">{{ form.nome }}</div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script src="{% static 'js/datatables.min.js' %}"></script>
<script src="{% static 'js/jqueryDataTable.js' %}"></script>

{% if show_modal %}
<script type="text/javascript">
    $(document).ready(function () {
        $("#staticBackdrop").modal('show');
    });
</script>
{% endif %}

<script>
    var Modal = document.getElementById('Modal')
    var Input = document.getElementById('Input')

    Modal.addEventListener('shown.bs.modal', function () {
        Input.focus()
    })
</script>
{% endblock %}

project/notafiscal/templates/notafiscal/notafiscalList.html
{% extends 'index.html' %}

{% load static %}

<title> {% block title %} Notas Fiscais {% endblock title%} </title>


{% block index %}

<div class="container">
    <div class="filters card border-1">
        <div class="card-header">
            <label class="fs-5 fw-bold">Notas Fiscais para Download</label>
        </div>
        <div class="table-responsive p-3">
            <table class="table table-sm" id="id_table">
                {% if message %}
                <div class="alert alert-warning" role="alert">
                    {{ message }}
                </div>
                {% endif %}
                <div class="col-12 d-flex justify-content-end">
                </div>
                <thead>
                    <tr>
                        <th>ChaveNFe</th>
                        <th>CNPJ</th>
                        <th>Nome</th>
                        <th>Emissão</th>
                        <th>Valor</th>
                        <th>Donwload</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                    <tr>
                        <td>{{ object.chNFe|truncatechars:20 }}</td>
                        <td>{{ object.CNPJ }}</td>
                        <td>{{ object.xNome|truncatechars:30 }}</td>
                        <td>{{ object.dhEmi|date:"d/m/y" }}</td>
                        <td>R$ {{ object.vNF|floatformat:2 }}</td>
                        <td align="center">
                            {% if exists %}
                            sim
                            {% else %}
                            <a href="{% url 'notafiscal:checkXml' chave=object.chNFe %}">Baixar</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="upload_xml" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="upload_xmlLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="upload_xmlLabel">Upload do arquivo XML</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form enctype="multipart/form-data" method="POST">
                    <div class=" card p-3">
                        <p>
                            Os dados da chave: {{ chave }} estão incompletos.
                            Acesse o site <a
                                href="http://hom.nfe.fazenda.gov.br/portal/consultaRecaptcha.aspx?tipoConsulta=resumo&tipoConteudo=7PhJ+gAVw2g="
                                target="_blank">Portal
                                da Nota Fiscal Eletrônica</a>
                            e baixe o arquivo XML.
                        </p>
                    </div>
                    <br> Selecione o arquivo XML baixado.
                    {% csrf_token %}
                    <div class="card"><input type="file" class="btn btn-light btn-sm" id="filexml" name="filexml"
                            required />
                    </div>
                    <p> <input type="submit" class="btn btn-primary btn-sm mt-2" value="Upload" /> </p>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script src="{% static 'js/datatables.min.js' %}"></script>
<script src="{% static 'js/jqueryDataTable.js' %}"></script>

{% if show_modal %}
<script type="text/javascript">
    $(document).ready(function () {
        $("#upload_xml").modal('show');
    });
</script>
{% endif %}

<script>
    function filtro() {
        let dataInicio = document.getElementById('data_ini')
        let datafim = document.getElementById('data_fim')
    };

    $(document).ready(function () {
        $('#id_table').DataTable({
            "pageLength": 100,
            "language": {
                "sProcessing": "Proccesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "Nenhum resultado encontrado",
                "sEmptyTable": "Nenhum dado disponivel",
                "sInfo": "Mostrando registros de _START_ a _END_ de um total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros de 0 a 0 de um total de 0 registros",
                "sInfoFiltered": "(filtrado de um total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Carregando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Seguinte",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Ativar para ordenar a coluna de maneira ascendente",
                    "sSortDescending": ": Ativar para ordenar a coluna de maneira descendente"
                }
            }
        });
    }); 
</script>
{% endblock %}