project/garantia/urls.py
from django.urls import path

from . import views as v


app_name = "garantia"


urlpatterns = [
    path("", v.produtosEmGarantia, name="produtosEmGarantia"),
    path("vendas/", v.vendasGarantiaList, name="vendasGarantiaList"),
    path("<venda>/", v.produtosVenda, name="produtosVenda"),
    path("<produto>/create/", v.produtoCreateGarantia, name="produtoCreateGarantia"),
    path(
        "<garantia>/list/timeline/", v.garantiaTimeLineList, name="garantiaTimeLineList"
    ),
    path(
        "<timeline>/update/timeline/",
        v.garantiaTimeLineUpdate,
        name="garantiaTimeLineUpdate",
    ),
]

project/project/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


from django.views.generic.base import TemplateView

# from .views import index

urlpatterns = [
    path("", TemplateView.as_view(template_name="account/login.html")),
    path("admin/", admin.site.urls),
    path(
        "index/",
        login_required(TemplateView.as_view(template_name="index.html")),
        name="index",
    ),
    path("accounts/", include("allauth.urls")),
    path("select2/", include("django_select2.urls")),
    path("compra/", include("compra.urls"), name="compra"),
    path("venda/", include("venda.urls"), name="venda"),
    path("mercadolivre/", include("mercadolivre.urls"), name="mercadolivre"),
    path("cliente/", include("cliente.urls"), name="cliente"),
    path("notafiscal/", include("notafiscal.urls"), name="notafiscal"),
    path("estoque/", include("estoque.urls"), name="estoque"),
    path("financeiro/", include("financeiro.urls"), name="financeiro"),
    path("despesa/", include("despesa.urls"), name="despesa"),
    path("receita/", include("receita.urls"), name="receita"),
    path("materiaprima/", include("materiaprima.urls"), name="materiaprima"),
    path("producao/", include("producao.urls"), name="producao"),
    path("transporte/", include("transportadora.urls"), name="transportadora"),
    path("expedicao/", include("expedicao.urls"), name="expedicao"),
    path("fornecedor/", include("fornecedor.urls"), name="fornecedor"),
    path("produto/", include("produto.urls"), name="produto"),
    path("suporte/", include("suporte.urls"), name="suporte"),
    path("representante/", include("representante.urls"), name="representante"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/venda/urls.py
from django.urls import path

from . import views as v


app_name = "venda"


urlpatterns = [
    path("", v.vendaList, name="vendaList"),
    path("ajax/", v.getVendasAjax, name="getVendasAjax"),
    path("relatorios/", v.relatorios, name="relatorios"),
    path("ano/", v.total_vendido_ano, name="total_vendido_ano"),
    path("mes/", v.total_vendido_mes, name="total_vendido_mes"),
    path("select/meses/", v.meses_ajax, name="meses_ajax"),
    # path("select/anos/", v.anos_ajax, name="anos_ajax"),
    path("cadastrar/", v.vendaCreate, name="vendaCreate"),
    path("cadastrar/preco/", v.produtoPrecoAjax, name="produtoPrecoAjax"),
    path("cadastrar/cliente/", v.clienteAjax, name="clienteAjax"),
    path("cadastrar/condicoes/parcelas/", v.condicaoAjax, name="condicaoAjax"),
    path("boletos/", v.boletoList, name="boletoList"),
    path("<hash>/orcamento/<int:id>/", v.orcamento, name="orcamento"),
    path("<int:pk>/editar/", v.vendaUpdate, name="vendaUpdate"),
    path("<int:pk>/clonevenda/", v.vendaClone, name="vendaClone"),
    path("<int:pk>/deletar/", v.vendaDelete, name="vendaDelete"),
    path("<int:pk>/nf/", v.vendaNF, name="vendaNF"),
    path("<int:pk>/expedicao/", v.expedicaoNF, name="expedicaoNF"),
    path(
        "<transportadora>/check/transporte/",
        v.listaConferenciaTransporteExpedicao,
        name="listaConferenciaTransporteExpedicao",
    ),
    path("<venda>/<cotacao>/deletar/cotacao/", v.deletarCotacao, name="deletarCotacao"),
]

project/garantia/models.py
from django.db import models
from django.utils.timezone import now


from venda.models import VendaProduto


class StatusGarantia(models.Model):
    nome = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Status Garantia"
        verbose_name_plural = "Status Garantias"

    def __str__(self):
        return self.nome


class Garantia(models.Model):
    produto = models.ForeignKey(VendaProduto, on_delete=models.CASCADE)
    data = models.DateTimeField(default=now)
    status = models.ForeignKey(StatusGarantia, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.produto} - {self.produto.venda}_{self.produto.venda.cliente}"


class StatusTimeLineGarantia(models.Model):
    nome = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Status TimeLine"
        verbose_name_plural = "Status TimeLines"

    def __str__(self):
        return self.nome


class GarantiaTimeLine(models.Model):
    garantia = models.ForeignKey(Garantia, on_delete=models.CASCADE)
    titulo = models.TextField()
    descricao = models.TextField()
    data = models.DateTimeField(default=now)
    status = models.ForeignKey(StatusTimeLineGarantia, on_delete=models.CASCADE)
    atualizadopor = models.CharField(max_length=255)

    class Meta:
        verbose_name = "TimeLine"
        verbose_name_plural = "TimeLines"
        ordering = ["-garantia"]

    def __str__(self):
        return f"Garantia({self.garantia.id}) - {self.garantia.produto.produto.nome} - TimeLine({self.id})"

    def save(self, *args, **kwargs):
        garantia = Garantia.objects.get(id=self.garantia.id)
        if self.status.nome == "Concluído":
            garantia.status = StatusGarantia.objects.get(nome=self.status.nome)
        else:
            garantia.status = StatusGarantia.objects.get(nome="Aberto")
        garantia.save()
        super(GarantiaTimeLine, self).save(*args, **kwargs)

project/garantia/forms.py
from django import forms


from .models import Garantia, GarantiaTimeLine


class GarantiaForm(forms.ModelForm):
    class Meta:
        model = Garantia
        fields = ["status"]
        widgets = {
            "status": forms.Select(
                attrs={
                    "class": "form-select",
                },
            ),
        }
        labels = {
            "status": "",
        }


class GarantiaTimeLineForm(forms.ModelForm):
    class Meta:
        model = GarantiaTimeLine
        fields = "__all__"
        exclude = ["garantia", "atualizadopor", "data"]
        widgets = {
            "titulo": forms.TextInput(
                attrs={
                    "class": "form-control",
                },
            ),
            "descricao": forms.Textarea(
                attrs={
                    "class": "form-control",
                },
            ),
            "status": forms.Select(
                attrs={
                    "class": "form-select",
                },
            ),
        }

project/garantia/views.py
import datetime
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from django.utils import timezone


from venda.models import Venda, VendaProduto
from .models import StatusGarantia, Garantia, GarantiaTimeLine
from .forms import GarantiaTimeLineForm


date_time = datetime.datetime.now().strftime(("%d/%m/%y %H:%M"))
today = timezone.now()


# lista de produtos na garantia(conserto)
class ProdutosEmGarantia(LoginRequiredMixin, ListView):
    template_name = "garantia/garantiaList.html"
    model = Garantia

    def get_queryset(self):
        status = StatusGarantia.objects.get(nome="Concluído")
        queryset = Garantia.objects.all().exclude(status=status)
        return queryset


produtosEmGarantia = ProdutosEmGarantia.as_view()


# lista de vendas com produtos na garantia
class VendasGarantiaList(LoginRequiredMixin, ListView):
    template_name = "garantia/vendasList.html"
    model = Venda


vendasGarantiaList = VendasGarantiaList.as_view()


# cria pedido de garantia do produto
# se o produto, referente à mesma venda, já estiver em garantia não aparece na lista
@login_required
def produtosVenda(request, venda):
    template_name = "garantia/produtosListCreate.html"
    # bdGarantia = Garantia.objects.filter(produto__venda=venda)
    bdProdutos = VendaProduto.objects.filter(venda=venda)
    # listaGarantia = []
    # for g in bdGarantia:
    #     listaGarantia.append(g.produto.produto.nome)
    produtos = {}
    for p in bdProdutos:
        # if not p.produto.nome in listaGarantia:
        produtos.update({p.id: p.produto})

    # mensagem = []
    # if not produtos:
    #     mensagem = "Todos os produtos desta venda já estão cadastrados para conserto."

    # context = {"produtos": produtos, "mensagem": mensagem}
    context = {"produtos": produtos}
    return render(request, template_name, context)


@login_required
def produtoCreateGarantia(request, produto):
    bd_produto = VendaProduto.objects.filter(pk=produto)
    status = get_object_or_404(StatusGarantia, nome="Aberto")
    for p in bd_produto:
        Garantia.objects.create(produto=p, status=status).save()
    return redirect("garantia:produtosEmGarantia")


def garantiaTimeLineList(request, garantia):
    template_name = "garantia/garantiaTimeline.html"
    dados = Garantia.objects.filter(pk=garantia)
    timeLine = GarantiaTimeLine.objects.filter(garantia=garantia).order_by("-id")

    bdDias = 0
    for i in timeLine:
        if i.status.nome == "Concluído":
            bdDias = i.data
    for d in dados:
        bdDias = d.data
    dias = abs((today - bdDias).days)

    form = GarantiaTimeLineForm(request.POST or None)
    garantiaForm = get_object_or_404(Garantia, pk=garantia)
    if request.method == "POST":
        if form.is_valid():
            form = form.save(commit=False)
            form.garantia = garantiaForm
            form.atualizadopor = f"por {request.user}_{date_time}"
            form.save()
            return HttpResponseRedirect(f"/garantia/{garantia}/list/timeline/")
        else:
            context = {
                "form": form,
                "dados": dados,
                "dias": dias,
                "garantia": garantia,
                "timeLine": timeLine,
            }
            return render(request, template_name, context)
    else:
        context = {
            "form": form,
            "dados": dados,
            "dias": dias,
            "garantia": garantia,
            "timeLine": timeLine,
        }
        return render(request, template_name, context)


def garantiaTimeLineUpdate(request, timeline):
    dados = GarantiaTimeLine.objects.filter(pk=timeline)
    objeto = get_object_or_404(GarantiaTimeLine, pk=timeline)
    template_name = "garantia/garantiaTimelineUpdate.html"

    bdDias = 0
    for d in dados:
        if d.garantia.status.nome == "Concluído":
            bdDias = d.data
        else:
            bdDias = d.garantia.data
    dias = abs((today - bdDias).days)

    idGarantia = 0
    for d in dados:
        idGarantia = d.garantia.id

    if request.method == "POST":
        form = GarantiaTimeLineForm(request.POST or None, instance=objeto)
        if form.is_valid():
            form = form.save(commit=False)
            form.garantia = objeto.garantia
            form.atualizadopor = f"por {request.user}_{date_time}"
            form.save()
            return HttpResponseRedirect(f"/garantia/{idGarantia}/list/timeline/")
        else:
            context = {
                "form": form,
                "dados": dados,
                "dias": dias,
                "garantia": idGarantia,
            }
            return render(request, template_name, context)
    else:
        form = GarantiaTimeLineForm(instance=objeto)
        context = {
            "form": form,
            "dados": dados,
            "dias": dias,
            "garantia": idGarantia,
        }
        return render(request, template_name, context)

project/garantia/templates/garantia/garantiaList.html
{% extends 'index.html' %}

{% load static %}

<title> {% block title %} Garantia {% endblock title%} </title>


{% block index %}

<div class="container">
    <div class="filters card border-1">
        <div class="card-header d-flex justify-content-between">
            <label class="fs-5 fw-bold">PRODUTOS NA GARANTIA</label>
        </div>
        <div class="p-3">
            <table class="table table-sm" id="id_table">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Produto</th>
                        <th>Venda</th>
                        <th>Cliente</th>
                        <th>Data compra</th>
                        <th>Vendedor</th>
                        <th>Status</th>
                        <th>TimeLine</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in object_list %}
                    <tr>
                        <td class="ps-4">{{ obj.id }}</td>
                        <td>{{ obj.produto }}</td>
                        <td>{{ obj.produto.venda }}</td>
                        <td>{{ obj.produto.venda.cliente|truncatechars:40 }}</td>
                        <td>{{ obj.produto.venda.data_pedido|date:"d/m/y" }}</td>
                        <td>{{ obj.produto.venda.vendedor }}</td>
                        <!-- <td id="status" class="bg-danger bg-opacity-50">{{ obj.status }}</td> -->
                        <td>{{ obj.status }}</td>
                        <td class="text-center pe-5">
                            <a href="{% url 'garantia:garantiaTimeLineList' garantia=obj.id %}">
                                <i class="fa fa-wrench" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

{% block script %}
<script src="{% static 'js/datatables.min.js' %}"></script>
<script src="{% static 'js/jqueryDataTable.js' %}"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $('#id_table').DataTable({
            "language": {
                "sProcessing": "Proccesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "Nenhum resultado encontrado",
                "sEmptyTable": "Nenhum dado disponivel",
                "sInfo": "Mostrando registros de _START_ a _END_ de um total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros de 0 a 0 de um total de 0 registros",
                "sInfoFiltered": "(filtrado de um total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Carregando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Seguinte",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Ativar para ordenar a coluna de maneira ascendente",
                    "sSortDescending": ": Ativar para ordenar a coluna de maneira descendente"
                }
            }
        });
    });
</script>


{% endblock %}

project/garantia/templates/garantia/garantiaTimeline.html
{% extends 'index.html' %}

{% load static %}

<title> {% block title %} TimeLine Garantia {% endblock title%} </title>

{% block index %}

<div class="container my-2">
    {% for d in dados %}
    <div class="card">
        <div class="card-header d-flex flex-wrap justify-content-center justify-content-lg-between">
            <h5>PRODUTO EM GARANTIA</h5>
            <h6 class="align-middle m-0 mt-lg-2">Há {{ dias|default:"0" }} dias em conserto</h6>
            <h6 class="align-middle m-0 mt-lg-2">Pedido aberto em {{ d.data|date:"d/m/Y H:m" }}</h6>
        </div>
        <div class="card-body cabecalho">
            <div class="d-flex justify-content-between">
                <h6 class="card-title">{{ d.produto }}</h6>
                <h6 class="card-title">Venda: {{ d.produto.venda }}</h6>
            </div>
            <div class="form-floating">
                <div class="row">
                    <div class="col-12 col-lg-6">
                        <label class="text-muted">Cliente</label>
                        <h6>{{ d.produto.venda.cliente }}</h6>
                    </div>
                    <div class="col-6 col-lg-2">
                        <label class="text-muted">Telefone</label>
                        <h6>{{ d.produto.venda.cliente.tel_principal }}</h6>
                    </div>
                    <div class="col-6 col-lg-2">
                        <label class="text-muted">Pedido da compra</label>
                        <h6>{{ d.produto.venda.data_pedido|date:"d/m/Y" }}</h6>
                    </div>
                    <div id="status" class="col-12 col-lg-2 text-center bg-warning bg-opacity-25 rounded">
                        <label class="text-muted">Status do pedido</label>
                        <h6 id="garantiaStatus">{{ d.status }}</h6>
                    </div>
                    <div class="col-12 col-lg-4">
                        <label class="text-muted">Rua</label>
                        <h6>{{ d.produto.venda.cliente.logradouro }}</h6>
                    </div>
                    <div class="col-2 col-lg-1">
                        <label class="text-muted">Número</label>
                        <h6>{{ d.produto.venda.cliente.numero }}</h6>
                    </div>
                    <div class="col-3 col-lg-1">
                        <label class="text-muted">Complemento</label>
                        <h6>{{ d.produto.venda.cliente.complemento }}</h6>
                    </div>
                    <div class="col-7 col-lg-2">
                        <label class="text-muted">Bairro</label>
                        <h6>{{ d.produto.venda.cliente.bairro }}</h6>
                    </div>
                    <div class="col-8 col-lg-3">
                        <label class="text-muted">Cidade/UF</label>
                        <h6>{{ d.produto.venda.cliente.cidade }}/{{ d.produto.venda.cliente.estado }}</h6>
                    </div>
                    <div class="col-4 col-lg-1">
                        <label class="text-muted">Cep</label>
                        <h6 style="font-size:14px;">{{ d.produto.venda.cliente.cep }}</h6>
                    </div>
                    <div class="col-6 col-lg-3">
                        <label class="text-muted">Vendedor</label>
                        <h6>{{ d.produto.venda.vendedor }}</h6>
                    </div>
                    <div class="col-12 col-lg-6">
                        <label class="text-muted">Transportadora</label>
                        <h6>{{ d.produto.venda.transportadora }}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="row">
        <div class="col-md-12 mt-2">
            <div class="d-flex justify-content-between">
                <h4>TimeLine</h4>
                <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" class="btnMaster px-2 "
                    href="">Nova
                    TimeLine
                    <i class="fa fa-plus-square" aria-hidden="true"></i>
                </a>
            </div>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Nova TimeLine</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form action="." method="post">
                            <div class="modal-body">
                                {% csrf_token %}
                                {{ form.non_field_errors }}
                                {{ form }}
                                {{ form.media }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary"
                                    data-bs-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary">Salvar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <ul class="timeline">
                {% for tl in timeLine %}
                <li class="bg-white rounded m-3">
                    <div class="d-flex justify-content-between p-1">
                        <a href="{% url 'garantia:garantiaTimeLineUpdate' timeline=tl.id %}"
                            class="label-color text-decoration-none text-uppercase fw-bold">
                            {{ tl.titulo }}</a>
                        <h6 class="label-color fw-bold">Status: {{ tl.status }}</h6>
                        <h6 class="label-color fw-bold float-end">{{ tl.data|date:"d/m/Y" }}</h6>
                    </div>
                    <p id="id_timeline" class="px-2 p-lg-3">{{ tl.descricao }}</p>
                    <h6 class="label-color float-lg-end">Atualizado {{ tl.atualizadopor }}</h6>
                </li><br>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}


{% block script %}

<script>
    var a = document.getElementById("garantiaStatus");
    var b = document.getElementById("status");
    if (a.innerHTML == 'Concluído') {
        console.log(a.innerHTML)
        b.setAttribute('class', "col-12 col-lg-2 text-center bg-success bg-opacity-25 rounded")
    }
</script>

{% endblock %}

project/garantia/templates/garantia/produtosListCreate.html
{% extends 'index.html' %}

{% load static widget_tweaks %}

<title> {% block title %} Garantia {% endblock title%} </title>


{% block index %}

<div class="container">
    <div class="filters card border-1">

        <div class="card-header d-flex justify-content-between">
            {% if mensagem %}
            <label class="fs-5 fw-bold">{{ mensagem }}</label>
            {% else %}
            <label class="fs-5 fw-bold">SELECIONE O PRODUTO</label>
            {% endif %}
        </div>
        <div class="d-flex gap-2 pt-2 ps-3">
            {% for pk, pv in produtos.items %}
            <a class="btn btn-primary btn-sm" href="{% url 'garantia:produtoCreateGarantia' produto=pk %}">{{ pv }}</a>
            <br>
            {% endfor %}
        </div>
        {% if mensagem %}
        <div class="text-end p-2"><a type=button class="btn btn-primary btn-sm"
                href="{% url 'garantia:vendasGarantiaList' %}">Sair</a></div>
        {% else %}
        <div class="text-end p-2 pt-0"><a type=button class="btn btn-secondary btn-sm"
                href="{% url 'garantia:vendasGarantiaList' %}">Cancelar</a></div>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block script %}
<script src="{% static 'js/datatables.min.js' %}"></script>
<script src="{% static 'js/jqueryDataTable.js' %}"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $('#id_table').DataTable({
            "language": {
                "sProcessing": "Proccesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "Nenhum resultado encontrado",
                "sEmptyTable": "Nenhum dado disponivel",
                "sInfo": "Mostrando registros de _START_ a _END_ de um total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros de 0 a 0 de um total de 0 registros",
                "sInfoFiltered": "(filtrado de um total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Carregando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Seguinte",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Ativar para ordenar a coluna de maneira ascendente",
                    "sSortDescending": ": Ativar para ordenar a coluna de maneira descendente"
                }
            }
        });
    });

</script>
{% endblock %}

project/garantia/templates/garantia/vendasList.html
{% extends 'index.html' %}

{% load static widget_tweaks %}

<title> {% block title %} Garantia {% endblock title%} </title>


{% block index %}

<div class="container">
    <div class="filters card border-1">
        <row>
            <div class="card-header d-flex justify-content-between">
                <label class="fs-5 fw-bold">NOVO PEDIDO DE GARANTIA</label>
            </div>
        </row>
        <div class="p-3">
            <table class="table table-sm" id="id_table">
                <thead>
                    <tr>
                        <th>Venda</th>
                        <th>Data compra</th>
                        <th>Cliente</th>
                        <th>Vendedor</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in object_list %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.data_pedido|date:"d/m/Y" }}</td>
                        <td>
                            <a href="{% url 'garantia:produtosVenda' obj.pk %}" style="font-size:12px;">
                                {{ obj.cliente }}
                            </a>
                        </td>
                        <td>{{ obj.vendedor }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}


{% block script %}
<script src="{% static 'js/datatables.min.js' %}"></script>
<script src="{% static 'js/jqueryDataTable.js' %}"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $('#id_table').DataTable({
            "language": {
                "sProcessing": "Proccesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "Nenhum resultado encontrado",
                "sEmptyTable": "Nenhum dado disponivel",
                "sInfo": "Mostrando registros de _START_ a _END_ de um total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros de 0 a 0 de um total de 0 registros",
                "sInfoFiltered": "(filtrado de um total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Carregando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Seguinte",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Ativar para ordenar a coluna de maneira ascendente",
                    "sSortDescending": ": Ativar para ordenar a coluna de maneira descendente"
                }
            }
        });
    });

</script>

{% endblock %}