project/producao/urls.py
from django.urls import path

from . import views as v

app_name = "producao"


urlpatterns = [
    path("estoque/previsao", v.previsaoEstoque, name="previsaoEstoque"),
    path("estoque/real", v.estoqueReal, name="estoqueReal"),
    path("iniciarproducao", v.iniciarProducao, name="iniciarProducao"),
    path("chaodefabrica", v.chaodeFabrica, name="chaodeFabrica"),
    path("relatorio/produto", v.relatorioProducao, name="relatorioProducao"),
    path("relatorio/venda", v.relatorioVenda, name="relatorioVenda"),
    path("enviarexpedicao", v.enviarExpedicao, name="enviarExpedicao"),
    path("edit_status_ajax", v.edit_status_ajax, name="edit_status_ajax"),
    path("criar_produto_ajax", v.criar_produto_ajax, name="criar_produto_ajax"),
    path("peca/estoque/previsao/", v.previsaoEstoquePecas, name="previsaoEstoquePecas"),
    path("peca/estoque/real/", v.estoqueRealPecas, name="estoqueRealPecas"),
]

project/project/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


from django.views.generic.base import TemplateView

# from .views import index

urlpatterns = [
    path("", TemplateView.as_view(template_name="account/login.html")),
    path("admin/", admin.site.urls),
    path(
        "index/",
        login_required(TemplateView.as_view(template_name="index.html")),
        name="index",
    ),
    path("accounts/", include("allauth.urls")),
    path("select2/", include("django_select2.urls")),
    path("compra/", include("compra.urls"), name="compra"),
    path("venda/", include("venda.urls"), name="venda"),
    path("mercadolivre/", include("mercadolivre.urls"), name="mercadolivre"),
    path("cliente/", include("cliente.urls"), name="cliente"),
    path("notafiscal/", include("notafiscal.urls"), name="notafiscal"),
    path("estoque/", include("estoque.urls"), name="estoque"),
    path("financeiro/", include("financeiro.urls"), name="financeiro"),
    path("despesa/", include("despesa.urls"), name="despesa"),
    path("receita/", include("receita.urls"), name="receita"),
    path("materiaprima/", include("materiaprima.urls"), name="materiaprima"),
    path("producao/", include("producao.urls"), name="producao"),
    path("transporte/", include("transportadora.urls"), name="transportadora"),
    path("expedicao/", include("expedicao.urls"), name="expedicao"),
    path("fornecedor/", include("fornecedor.urls"), name="fornecedor"),
    path("produto/", include("produto.urls"), name="produto"),
    path("suporte/", include("suporte.urls"), name="suporte"),
    path("representante/", include("representante.urls"), name="representante"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/venda/urls.py
from django.urls import path

from . import views as v


app_name = "venda"


urlpatterns = [
    path("", v.vendaList, name="vendaList"),
    path("ajax/", v.getVendasAjax, name="getVendasAjax"),
    path("relatorios/", v.relatorios, name="relatorios"),
    path("ano/", v.total_vendido_ano, name="total_vendido_ano"),
    path("mes/", v.total_vendido_mes, name="total_vendido_mes"),
    path("select/meses/", v.meses_ajax, name="meses_ajax"),
    # path("select/anos/", v.anos_ajax, name="anos_ajax"),
    path("cadastrar/", v.vendaCreate, name="vendaCreate"),
    path("cadastrar/preco/", v.produtoPrecoAjax, name="produtoPrecoAjax"),
    path("cadastrar/cliente/", v.clienteAjax, name="clienteAjax"),
    path("cadastrar/condicoes/parcelas/", v.condicaoAjax, name="condicaoAjax"),
    path("boletos/", v.boletoList, name="boletoList"),
    path("<hash>/orcamento/<int:id>/", v.orcamento, name="orcamento"),
    path("<int:pk>/editar/", v.vendaUpdate, name="vendaUpdate"),
    path("<int:pk>/clonevenda/", v.vendaClone, name="vendaClone"),
    path("<int:pk>/deletar/", v.vendaDelete, name="vendaDelete"),
    path("<int:pk>/nf/", v.vendaNF, name="vendaNF"),
    path("<int:pk>/expedicao/", v.expedicaoNF, name="expedicaoNF"),
    path(
        "<transportadora>/check/transporte/",
        v.listaConferenciaTransporteExpedicao,
        name="listaConferenciaTransporteExpedicao",
    ),
    path("<venda>/<cotacao>/deletar/cotacao/", v.deletarCotacao, name="deletarCotacao"),
]

project/producao/models.py
from django.db import models
from datetime import datetime
from pytz import timezone
from django.contrib.auth.models import User

from produto.models import Produto, Peca
from materiaprima.models import MateriaPrima
from funcionario.models import Funcionario

StatusProdutoAcabado = (
    ("faltandomateriaprima", "Faltando Materia Prima"),
    ("montagem", "Montagem"),
    ("eletrica", "Elétrica"),
    ("refrigeracao", "Refrigeração"),
    ("acabamento", "Acabamento"),
    ("embalagem", "Embalagem"),
    ("estoque", "Estoque"),
)


class LimiteProducaoDiaria(models.Model):
    produto = models.OneToOneField(
        Produto, blank=False, primary_key=True, on_delete=models.CASCADE
    )
    quantidade = models.IntegerField(default=0)

    # def __str__(self):
    #     return str(self.produto)


class LimiteProducaoDiariaPeca(models.Model):
    peca = models.OneToOneField(
        Peca, blank=False, primary_key=True, on_delete=models.CASCADE
    )
    quantidade = models.IntegerField(default=0)

    def __str__(self):
        return str(self.peca)


# Create your models here.
class Setor(models.Model):
    nome = models.CharField(max_length=200)


class ProdutoAcabado(models.Model):
    numeroserie = models.CharField(max_length=200, null=False, blank=True)
    valor_venda = models.DecimalField(max_digits=11, decimal_places=2, default=0.00)
    valor_custototal = models.FloatField(null=True, blank=True)
    valor_custo_material = models.FloatField(null=True, blank=True)
    valor_custo_imposto = models.FloatField(null=True, blank=True)
    valor_custo_producao = models.FloatField(null=True, blank=True)
    valor_custo_administracao = models.FloatField(null=True, blank=True)
    valor_custo_venda = models.FloatField(null=True, blank=True)
    data_producao = models.DateTimeField(null=True, blank=True)
    status = models.CharField(
        choices=StatusProdutoAcabado, default="montagem", max_length=255
    )
    produto = models.ForeignKey(
        Produto, on_delete=models.RESTRICT, null=True, blank=True
    )
    hora_inicio = models.DateTimeField(blank=False, null=False)
    hora_fim = models.DateTimeField(auto_now=True, blank=False, null=False)
    hora_momento = models.DateTimeField(auto_now=True, blank=False, null=False)
    duracao = models.FloatField(default=0, blank=False, null=False)

    class Meta:
        verbose_name = "PRODUTO ACABADO"
        verbose_name_plural = "PRODUTOS ACABADOS"

    def __str__(self):
        if not self.produto:
            import pdb

            pdb.set_trace()
        return str(self.produto.nome)

    def get_nome_abreviado(self):
        return self.produto.nome.replace("Bebedouro", "")

    def get_hora_inicio(self):
        return self.hora_inicio.strftime("%H:%M")

    def get_tempo(self):
        diferenca = datetime.now().astimezone(
            timezone("America/Sao_Paulo")
        ) - self.hora_momento.astimezone(timezone("America/Sao_Paulo"))
        return str(round(diferenca.total_seconds() / 60 / 60, 2)).replace(".", ":")

    def get_tempototal(self):
        diferenca = datetime.now().astimezone(
            timezone("America/Sao_Paulo")
        ) - self.hora_inicio.astimezone(timezone("America/Sao_Paulo"))
        return str(round(diferenca.total_seconds() / 60 / 60, 2)).replace(".", ":")

    def get_momento(self):
        diferenca = datetime.now().astimezone(
            timezone("America/Sao_Paulo")
        ) - self.hora_momento.astimezone(timezone("America/Sao_Paulo"))
        diferenca_atual = diferenca.total_seconds() / 60  # minutos
        diferenca_esperada = TempoDesejadoProducao.objects.filter(status=self.status)
        if diferenca_esperada:
            diferenca_esperada = diferenca_esperada[0]
            if diferenca_atual < diferenca_esperada.tempo_verde:
                return "green"
            elif diferenca_atual < diferenca_esperada.tempo_amarelo:
                return "yellow"
            else:
                return "red"


class PecaAcabada(models.Model):
    peca = models.ForeignKey(Peca, on_delete=models.RESTRICT, null=True)
    quantidade = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.0,
    )
    dataproducao = models.DateField()
    usuario = models.ForeignKey(User, on_delete=models.RESTRICT)
    criadoem = models.DateTimeField(auto_now_add=True)
    atualizadoem = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "PEÇA"
        verbose_name_plural = "PEÇAS"

    def __str__(self):
        return self.peca


class HistoricoMontagem(models.Model):
    produtoacabado = models.ForeignKey(
        ProdutoAcabado, on_delete=models.CASCADE, verbose_name="PRODUTOACABADO"
    )
    hora_inicio = models.DateTimeField(auto_now=True, blank=False, null=False)
    hora_fim = models.DateTimeField(auto_now=True, blank=False, null=False)
    duracao = models.FloatField(default=0, blank=False, null=False)
    status = models.CharField(
        choices=StatusProdutoAcabado, default="montagem", max_length=255
    )


class TempoDesejadoProducao(models.Model):
    status = models.CharField(
        choices=StatusProdutoAcabado, default="montagem", max_length=255
    )
    tempo_verde = models.FloatField(default=0, blank=False, null=False)
    tempo_amarelo = models.FloatField(default=0, blank=False, null=False)


class MateriaPrimaProdutoAcabado(models.Model):
    produtoacabado = models.ForeignKey(
        ProdutoAcabado, on_delete=models.RESTRICT, verbose_name="PRODUTO"
    )
    materiaprimausada = models.ForeignKey(
        MateriaPrima, on_delete=models.RESTRICT, verbose_name="MATERIA PRIMA"
    )
    valor = models.DecimalField(
        "VALOR CUSTO", max_digits=9, decimal_places=2, default=0, null=True, blank=True
    )

    class Meta:
        verbose_name = "MATÉRIA PRIMA PRODUTO ACABADO"
        verbose_name_plural = "MATÉRIA PRIMA PRODUTOS ACABADOS"

    def __str__(self):
        return str(self.produtoacabado)


class Montadores(models.Model):
    funcionario = models.ForeignKey(Funcionario, on_delete=models.RESTRICT, null=True)
    setor_montagem = models.ForeignKey(Setor, on_delete=models.RESTRICT, null=True)


class PrevisaoEstoque(models.Model):
    producao = models.IntegerField()

project/producao/forms.py
from django import forms
from producao.models import LimiteProducaoDiaria


class QuantidadeProducaoForm(forms.ModelForm):
    class Meta:
        model = LimiteProducaoDiaria
        fields = ("produto", "quantidade")
        widgets = {
            "produto": forms.Select(
                attrs={
                    "class": "form-control form-control-sm fw-bold text-end w-50 m-1"
                }
            ),
            "quantidade": forms.NumberInput(
                attrs={
                    "class": "form-control form-control-sm fw-bold text-center w-25 m-1"
                }
            ),
        }
        labels = {
            "produto": "",
            "quantidade": "",
        }


# class QuantidadePecaForm(forms.ModelForm):
#     class Meta:
#         model = LimiteProducaoDiariaPeca
#         fields = ("peca", "quantidade")
#         widgets = {
#             "peca": forms.Select(
#                 attrs={
#                     "class": "form-control form-control-sm fw-bold text-end w-50 m-1"
#                 }
#             ),
#             "quantidade": forms.NumberInput(
#                 attrs={
#                     "class": "form-control form-control-sm fw-bold text-center w-25 m-1"
#                 }
#             ),
#         }
#         labels = {
#             "peca": "",
#             "quantidade": "",
#         }

project/producao/templates/producao/chaodefabrica.html
{% extends 'index.html' %}

{% load static %}

<title> {% block title %} Chão de Fabrica {% endblock title%} </title>

{% block index %}

<head>
    <meta http-equiv="refresh" content="60">
</head>

<script>
    function cria_produto(id_produto) {
        $.ajax({
            url: "{% url 'producao:criar_produto_ajax' %}",
            data: { 'id_produto': id_produto },
            cache: false,
            success: function (html) {
                location.reload();
            }
        });
    }
    function change_status(id, status) {
        $.ajax({
            url: "{% url 'producao:edit_status_ajax' %}",
            data: { 'id': id, 'status': status },
            cache: false,
            success: function (html) {
                location.reload();
            }
        });
    }
</script>

<style>
    .board {
        display: flex;
        justify-content: center;
        margin-top: 50px;
        height: 1000px
    }

    .card2 {
        background: #3F4447;
        padding: 10px;
        margin-bottom: 10px;
        border-radius: 3px;
        border-bottom: 2px;
        cursor: pointer;
        width: 150px;
        height: 60px;
        cursor: grab;
        transition: all 0.3s cubic-bezier(0.4, 0.0, 0.2, 1);
        border: 1px solid #3F4447;
    }

    .card2 h4 {
        font-size: 1.2rem;
    }

    main .card:active {
        cursor: grabbing;
    }

    main .card.dragging {
        opacity: .5;
        transform: scale(.8);
    }

    .column {
        padding: 10px;
        background: white;
        border: 2px solid white;
        transition: all 0.3s cubic-bezier(0.4, 0.0, 0.2, 1);
    }

    main .green {
        background-color: #3DED07;
    }

    main .yellow {
        background-color: #F6F943;
    }

    main .red {
        background-color: #DA2427;
    }

    .hidden {
        display: none;
    }

    .show {
        display: show;
    }


    .column.column-todo h2 {
        background: #3498DB;
    }

    .column.column-ip h2 {
        background: #F39C12;
    }

    .column.column-ip {
        margin: 0 20px;
    }

    .column.drop {
        border: 2px dashed #3F4447;
    }

    .column.drop article {
        pointer-events: none;
    }

    h3 {
        font-size: 21px;
        font-family: Helvetica;
        margin: 0;
    }

    .card:last-child {
        margin-bottom: 0;
    }

    h2 {
        background: rgb(145, 85, 253);
        margin: -10px -10px 10px;
        padding: 4px 10px;
        font-family: Helvetica;
        font-size: 21px;
    }

    h2 center {
        color: white;
    }
</style>

<div class="container">
    <div class="card-header">
        <label class="fs-5 fw-bold">Bebedouros em produção</label>
    </div>
    <div class="container">
        <div class="row gap-3 justify-content-center">
            {%for produto in lista_produtos%}
            <div class="card col-12 col-md align-items-start p-4 bg-light">
                <div class="box d-flex gap-4">
                    <div onMouseOver="this.style.cursor='pointer'" onclick="javascript:cria_produto({{produto.id}})"
                        class="imageBlock d-flex justify-content-center align-items-center bg-white">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path fill="currentColor"
                                d="M20 21H4V10h2v9h12v-9h2v11M3 3h18v6H3V3m6.5 8h5c.28 0 .5.22.5.5V13H9v-1.5c0-.28.22-.5.5-.5M5 5v2h14V5H5Z"
                                style="color: rgb(145, 85, 253);" />
                        </svg>
                    </div>
                    <div class="">
                        <span class="">{{produto.get_nome_abreviado}}</span>
                        <div class="d-flex align-items-center justify-content-end">
                            <h6 class="" style="color: rgb(86, 202, 0);">{{produto.quantidade_em_producao}}</h6>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>



    <div class="card-header my-3">
        <legend class="fs-5 fw-bold mb-0">Relatórios</legend>
        <a href="{% url 'producao:relatorioProducao' %}" class="btn btn-primary btn-sm">Produtos</a>
        <a href="{% url 'producao:relatorioVenda' %}" class="btn btn-primary btn-sm">Vendas</a>
    </div>


    <hr>
    <main class="board justify-content-between mt-2">
        <div class="column" ondrop="drop(event)" ondragover="allowDrop(event)" data-status="excluir">
            <h2>Excluir <br />&nbsp;</h2>
            {%for produto in excluir%}
            <article class="card2 {{produto.get_momento}}" draggable="true" ondragstart="drag(event)"
                data-id="{{produto.id}}">
                <h3>{{produto.get_nome_abreviado}}&nbsp&nbsp{{produto.get_tempototal}}</h3>
                <h4>{{produto.get_tempo}}</h4>
            </article>
            {%endfor%}
        </div>
        <div class="column" ondrop="drop(event)" ondragover="allowDrop(event)" data-status="faltandomateriaprima">
            <h2>Faltando peças <br />
                <center>{{media_faltandomateriaprima}}</center>
            </h2>
            {%for produto in faltandomateriaprima%}
            <article class="card2 {{produto.get_momento}}" draggable="true" ondragstart="drag(event)"
                data-id="{{produto.id}}">
                <h3>{{produto.get_nome_abreviado}}&nbsp&nbsp{{produto.get_tempototal}}</h3>
                <h4>{{produto.get_tempo}}</h4>
            </article>
            {%endfor%}
        </div>
        <div class="column" ondrop="drop(event)" ondragover="allowDrop(event)" data-status="montagem">
            <h2>Montagem <br />
                <center>{{media_montagem}}</center>
            </h2>
            {%for produto in montagem%}
            <article class="card2 {{produto.get_momento}}" draggable="true" ondragstart="drag(event)"
                data-id="{{produto.id}}">
                <h3>{{produto.get_nome_abreviado}}&nbsp&nbsp{{produto.get_tempototal}}</h3>
                <h4>{{produto.get_tempo}}</h4>
            </article>
            {%endfor%}
        </div>
        <div class="column" ondrop="drop(event)" ondragover="allowDrop(event)" data-status="eletrica">
            <h2>Elétrica <br />
                <center>{{media_eletrica}}</center>
            </h2>
            {%for produto in eletrica%}
            <article class="card2 {{produto.get_momento}}" draggable="true" ondragstart="drag(event)"
                data-id="{{produto.id}}">
                <h3>{{produto.get_nome_abreviado}}&nbsp&nbsp{{produto.get_tempototal}}</h3>
                <h4>{{produto.get_tempo}}</h4>
            </article>
            {%endfor%}
        </div>
        <div class="column" ondrop="drop(event)" ondragover="allowDrop(event)" data-status="refrigeracao">
            <h2>Refrigeração <br />
                <center>01:12</center>
            </h2>
            {%for produto in refrigeracao%}
            <article class="card2 {{produto.get_momento}}" draggable="true" ondragstart="drag(event)"
                data-id="{{produto.id}}" ondxxblclick="adiciona_input(this)">
                <h3>{{produto.get_nome_abreviado}}&nbsp&nbsp{{produto.get_tempototal}}</h3>
                <h4>{{produto.get_tempo}}</h4>
            </article>
            {%endfor%}
        </div>
        <div class="column" ondrop="drop(event)" ondragover="allowDrop(event)" data-status="acabamento">
            <h2>Acabamento <br />
                <center>{{media_acabamento}}</center>
            </h2>
            {%for produto in acabamento%}
            <article class="card2 {{produto.get_momento}}" draggable="true" ondragstart="drag(event)"
                data-id="{{produto.id}}">
                <h3>{{produto.get_nome_abreviado}}&nbsp&nbsp{{produto.get_tempototal}}</h3>
                <h4>{{produto.get_tempo}}</h4>
            </article>
            {%endfor%}
        </div>
        <div class="column" ondrop="drop(event)" ondragover="allowDrop(event)" data-status="embalagem">
            <h2>Embalagem <br />
                <center>{{media_embalagem}}</center>
            </h2>
            {%for produto in embalagem%}
            <article class="card2 {{produto.get_momento}}" draggable="true" ondragstart="drag(event)"
                data-id="{{produto.id}}">
                <h3>{{produto.get_nome_abreviado}}&nbsp&nbsp{{produto.get_tempototal}}</h3>
                <h4>{{produto.get_tempo}}</h4>
            </article>
            {%endfor%}
        </div>
        <div class="column" ondrop="drop(event)" ondragover="allowDrop(event)" data-status="estoque">
            <h2>Estoque <br />
                <center>{{media_estoque}}</center>
            </h2>
            </h2>
            {%for produto in estoque%}
            <article class="card2 {{produto.get_momento}}" draggable="true" ondragstart="drag(event)"
                data-id="{{produto.id}}">
                <h3>{{produto.get_nome_abreviado}}&nbsp&nbsp{{produto.get_tempototal}}</h3>
                <h4>{{produto.get_tempo}}</h4>
            </article>
            {%endfor%}
        </div>
    </main>
    <script src="{% static 'js/drag-n-drop.js' %}"></script>

</div>
</div>

{% endblock %}

project/producao/templates/producao/imprimirProducao.html
{% extends 'index.html' %}

{% load static %}

<title> {% block title %} Produção {% endblock title%} </title>

{% block index %}
<style>
    @media print {
        body * {
            visibility: hidden;
        }

        button,
        button * {
            display: none !important;
        }

        #content,
        #content * {
            visibility: visible;
        }

        #content {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
        }
    }
</style>

<body>
    <div class="container">
        <div class="filters my-2 p-3" id="content">
            <div class="d-flex justify-content-between">
                <label class="fs-5 fw-bold">Relatório de Produtos</label>
                <button class="btn btn-primary btn-sm" onclick="window.print()">Imprimir</button>
            </div>
            {% for prod in produto %}
            <div class="card mt-1">
                <div class="card-header">
                    <h5 class="mb-0">{{ prod }}</h5>
                </div>
                <table class="table table-sm" id="id_table">
                    <thead>
                        <tr>
                            <th>Série</th>
                            <th>Situação</th>
                            <th>Produção</th>
                            <th>Inicio</th>
                            <th>Fim</th>
                            <th>Duracao</th>
                        </tr>
                    </thead>
                    {% for p in producao %}
                    {% if prod == p.produto %}
                    <tbody>
                        <tr>
                            <td>{{ p.numeroserie }}</td>
                            <td>{{ p.status }}</td>
                            <td>{{ p.data_producao|default:''}}</td>
                            <td>{{ p.hora_inicio|date:'d/m/Y H:i'}}</td>
                            <td>{{ p.hora_fim|date:'d/m/Y H:i'}}</td>
                            <td>{{ p.duracao }}</td>
                        </tr>
                    </tbody>
                    {% endif %}
                    {% endfor %}
                </table>
            </div>
            {% endfor %}
        </div>
    </div>
</body>

{% endblock %}

project/producao/templates/producao/previsaoEstoque copy.html
{% extends 'index.html' %}

{% load static %}
{% load widget_tweaks %}

<title> {% block title %} Previsão de Estoque {% endblock title%} </title>

{% block index %}
<div class="container px-2">
    <!-- <div class="d-flex gap-5 justify-content-between mb-2 px-1"> -->
    <div class="d-flex gap-5 mb-2 px-1">
        <h6 class="fw-bold">PREVISÃO DE ESTOQUE</h6>
        <!-- <div class="d-flex">
            <h6 class="text-end m-auto me-2">Quantidade por dia -></h6>
            <input class="form-control form-control-sm justify-content-end fw-bold fs-3 text-center" type="text" id="id_quantidade" style="width: 100px;" onchange="quantidadeProduzir()">
        </div> -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Quantidade
        </button>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Insira a Quantidade para cada Produto</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <!-- <form method="POST">
                    <div class="modal-body">
                        {% csrf_token %}
                        {{ formset.management_form }}
                        {% for form in formset %}
                        <div class="card-body pt-0">
                            <div class="row justify-content-evenly pb-0">
                                {{ form.produto }} - {{ form.quantidade }}
                            </div>
                        </div>
                        {% endfor %}
                    </div>                    
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary btn-sm">Salvar</button>
                </div>
                </form> -->
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ formset.management_data }}
                    {{ formset.as_p }}

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary btn-sm">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="overflow-auto card py-2 px-3">
        <div class="d-flex gap-3 p-2 ps-0">
            <div class="col-4 col-lg-2">
                <h6>Produto</h6>
                <h6 class="pt-1 mb-1" style="font-size: 16px;" align="right">Dias</h6>
                <h6 align="right">{{ produto }}</h6>
                {% for ikey in nome_materia_prima %}
                <h6 class="text-muted" style="font-size: 12px;" align="right">{{ ikey }}</h6>
                {% endfor %}
            </div>
            <div class="d-flex flex-column w-100" style="min-width:992px;">
                <div class="d-flex gap-3 justify-content-around bg-secondary text-white rounded">
                    {% for m in meses %}
                    <h5 class="m-1">{{ m }}</h5>
                    <br>
                    {% endfor %}
                </div>
                <div class="d-flex justify-content-around">
                    {% for d in dias %}
                    <div class="row justify-content-center align-items-center text-muted w-100"
                        style="font-size: 12px;">
                        {{ d }}
                    </div>
                    {% endfor %}
                </div>
                <div class="d-flex justify-content-around mt-1">
                    {% for p in prod_diaria %}
                    <div class="pro-diaria row justify-content-center align-items-center text-muted w-100 mt-1"
                        style="font-size: 12px;">
                        {{ p }}
                    </div>
                    {% endfor %}
                </div>
                {% for mp in materia_prima %}
                <div class="mp d-flex justify-content-around text-muted pt-1" id="{{ mp }}">
                    {% for p in mp %}
                    <div class="mat-prima row justify-content-center align-items-center w-100" style="font-size: 12px;"
                        id="{{ mp }}-{{ forloop.counter }}">
                        {{ p }}
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="hidden" id="total">
    {{ previsao_dias }}
</div>
{% endblock %}


{% block script %}
<script>

    function range(start, end) {
        const ans = [];
        for (let i = start; i <= end; i++) {
            ans.push(i);
        }
        return ans;
    }


    $('.mp .mat-prima').each(function () {
        var id = $(this).attr('id');
        var vlr = document.getElementById(id).innerText;
        // if (vlr == 0) {
        //     document.getElementById(id).style.fontWeight = 'bolder';
        //     document.getElementById(id).style.color = 'gold';
        // }
        if (vlr < 0) {
            document.getElementById(id).style.fontWeight = 'bolder';
            document.getElementById(id).style.color = 'red';
        }
    });

</script>
{% endblock %}