project/project/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


from django.views.generic.base import TemplateView

# from .views import index

urlpatterns = [
    path("", TemplateView.as_view(template_name="account/login.html")),
    path("admin/", admin.site.urls),
    path(
        "index/",
        login_required(TemplateView.as_view(template_name="index.html")),
        name="index",
    ),
    path("accounts/", include("allauth.urls")),
    path("select2/", include("django_select2.urls")),
    path("compra/", include("compra.urls"), name="compra"),
    path("venda/", include("venda.urls"), name="venda"),
    path("mercadolivre/", include("mercadolivre.urls"), name="mercadolivre"),
    path("cliente/", include("cliente.urls"), name="cliente"),
    path("notafiscal/", include("notafiscal.urls"), name="notafiscal"),
    path("estoque/", include("estoque.urls"), name="estoque"),
    path("financeiro/", include("financeiro.urls"), name="financeiro"),
    path("despesa/", include("despesa.urls"), name="despesa"),
    path("receita/", include("receita.urls"), name="receita"),
    path("materiaprima/", include("materiaprima.urls"), name="materiaprima"),
    path("producao/", include("producao.urls"), name="producao"),
    path("transporte/", include("transportadora.urls"), name="transportadora"),
    path("expedicao/", include("expedicao.urls"), name="expedicao"),
    path("fornecedor/", include("fornecedor.urls"), name="fornecedor"),
    path("produto/", include("produto.urls"), name="produto"),
    path("suporte/", include("suporte.urls"), name="suporte"),
    path("representante/", include("representante.urls"), name="representante"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/receita/urls.py
from django.urls import path

from . import views as v


app_name = 'receita'


urlpatterns = [
    path('', v.receitaList, name='receitaList'),
    path('cadastrar/', v.receitaCreate, name='receitaCreate'),
    path('<int:pk>/detalhes/', v.receitaDetails, name='receitaDetails'),
    path('<int:pk>/editar/', v.receitaUpdate, name='receitaUpdate'),
    path('<int:pk>/deletar/', v.receitaDelete, name='receitaDelete')
]

project/venda/urls.py
from django.urls import path

from . import views as v


app_name = "venda"


urlpatterns = [
    path("", v.vendaList, name="vendaList"),
    path("ajax/", v.getVendasAjax, name="getVendasAjax"),
    path("relatorios/", v.relatorios, name="relatorios"),
    path("ano/", v.total_vendido_ano, name="total_vendido_ano"),
    path("mes/", v.total_vendido_mes, name="total_vendido_mes"),
    path("select/meses/", v.meses_ajax, name="meses_ajax"),
    # path("select/anos/", v.anos_ajax, name="anos_ajax"),
    path("cadastrar/", v.vendaCreate, name="vendaCreate"),
    path("cadastrar/preco/", v.produtoPrecoAjax, name="produtoPrecoAjax"),
    path("cadastrar/cliente/", v.clienteAjax, name="clienteAjax"),
    path("cadastrar/condicoes/parcelas/", v.condicaoAjax, name="condicaoAjax"),
    path("boletos/", v.boletoList, name="boletoList"),
    path("<hash>/orcamento/<int:id>/", v.orcamento, name="orcamento"),
    path("<int:pk>/editar/", v.vendaUpdate, name="vendaUpdate"),
    path("<int:pk>/clonevenda/", v.vendaClone, name="vendaClone"),
    path("<int:pk>/deletar/", v.vendaDelete, name="vendaDelete"),
    path("<int:pk>/nf/", v.vendaNF, name="vendaNF"),
    path("<int:pk>/expedicao/", v.expedicaoNF, name="expedicaoNF"),
    path(
        "<transportadora>/check/transporte/",
        v.listaConferenciaTransporteExpedicao,
        name="listaConferenciaTransporteExpedicao",
    ),
    path("<venda>/<cotacao>/deletar/cotacao/", v.deletarCotacao, name="deletarCotacao"),
]

project/receita/models.py
from django.db import models
from django.urls import reverse_lazy as _

from fornecedor.models import Fornecedor
from cliente.models import Cliente


class Categoria(models.Model):
    nome = models.CharField("Nome", max_length=200)
    descricao = models.TextField("Descrição", blank=True, null=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"


class Receita(models.Model):
    usuario = models.CharField(max_length=255, null=True, blank=True)
    nome = models.CharField(max_length=200, null=True, blank=True)
    total = models.DecimalField(max_digits=11, decimal_places=2, default=0.00)
    criadoem = models.DateTimeField(auto_now_add=True)
    atualizadoem = models.DateTimeField(auto_now=True)
    categoria1 = models.ForeignKey(Categoria, on_delete=models.RESTRICT)
    categoria2 = models.ForeignKey(
        Categoria, on_delete=models.RESTRICT, related_name="categoria2"
    )
    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.RESTRICT, null=True)
    num_parcelas = models.IntegerField(default=0)
    descricao = models.TextField(blank=True, null=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.RESTRICT)

    class Meta:
        verbose_name = "RECEITA"
        verbose_name_plural = "RECEITAS"

    def __str__(self):
        return self.nome

    def receita_gau_detail(self):
        return _("receita:receitaDetails", args=[self.pk])

    def receita_gau_edit(self):
        return _("receita:receitaUpdate", args=[self.pk])

    def receita_gau_delete(self):
        return _("receita:receitaDelete", args=[self.pk])

project/receita/forms.py
from django import forms

from .models import Receita


class ReceitaForm(forms.ModelForm):
    class Meta:
        model = Receita
        fields = (
            "nome",
            "total",
            "categoria1",
            "categoria2",
            "num_parcelas",
            "descricao",
            "cliente",
        )
        widgets = {
            "nome": forms.TextInput(
                attrs={
                    "class": "form-control form-control.sm",
                    "style": "font-size:12px;",
                }
            ),
            "total": forms.NumberInput(
                attrs={"class": "form-control form-control-sm text-end"}
            ),
            "categoria1": forms.Select(attrs={"class": "form-select form-select-sm"}),
            "categoria2": forms.Select(attrs={"class": "form-select form-select-sm"}),
            "num_parcelas": forms.NumberInput(
                attrs={"class": "form-control form-control-sm text-center"}
            ),
            "descricao": forms.TextInput(
                attrs={
                    "class": "form-control form-control.sm",
                    "style": "font-size:12px;",
                }
            ),
            # 'fornecedor': forms.Select(attrs={'class': 'form-select form-select-sm'}),
            "cliente": forms.Select(attrs={"class": "form-select form-select-sm"}),
        }

    def __init__(self, *args, **kwargs):
        super(ReceitaForm, self).__init__(*args, **kwargs)
        self.fields["total"].widget.attrs["readonly"] = True
        self.fields["num_parcelas"].widget.attrs["readonly"] = True

project/receita/views.py
from django.urls import reverse_lazy as _
from django.shortcuts import redirect, render
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.views.generic.edit import DeleteView


from .models import Receita
from .forms import ReceitaForm
from financeiro.models import ContaReceber
from financeiro.forms import ContaReceberForm


success_url_receita = _("receita:receitaList")
template_name_createreceita = "receita/receitaCreateUpdate.html"


@login_required
def receitaCreate(request):
    titulo = "Nova Receita"
    form = ReceitaForm(request.POST or None)
    Formset_contaReceber_Factory = inlineformset_factory(
        Receita,
        ContaReceber,
        form=ContaReceberForm,
        min_num=1,
        extra=0,
        can_delete=False,
    )
    parcela_form = Formset_contaReceber_Factory(
        request.POST or None, request.FILES or None
    )

    if request.method == "POST":
        if form.is_valid() and parcela_form.is_valid():
            # form.save()
            usuario = form.save(commit=False)
            usuario.usuario = str(request.user)
            usuario.save()
            # receita = form.save()
            parcela_form.instance = usuario
            parcela_form.save()
            return redirect(success_url_receita)
        else:
            context = {
                "titulo": titulo,
                "form": form,
                "parcela": parcela_form,
            }
            return render(request, template_name_createreceita, context)
    else:
        context = {
            "titulo": titulo,
            "form": form,
            "parcela": parcela_form,
        }
        return render(request, template_name_createreceita, context)


@login_required
def receitaUpdate(request, pk):
    titulo = "Editar Receita"
    objeto = get_object_or_404(Receita, pk=pk)
    form = ReceitaForm(request.POST or None, instance=objeto)
    Formset_contaReceber_Factory = inlineformset_factory(
        Receita, ContaReceber, form=ContaReceberForm, extra=0, can_delete=False
    )
    parcela_form = Formset_contaReceber_Factory(
        request.POST or None,
        request.FILES or None,
        instance=objeto,
    )

    if request.method == "POST":
        if form.is_valid() and parcela_form.is_valid():
            receita = form.save()
            parcela_form.instance = receita
            parcela_form.save()
            return redirect(success_url_receita)
        else:
            codigo = True
            context = {
                "codigo": codigo,
                "titulo": titulo,
                "form": form,
                "parcela": parcela_form,
            }
            return render(request, template_name_createreceita, context)
    else:
        codigo = True
        context = {
            "codigo": codigo,
            "titulo": titulo,
            "form": form,
            "parcela": parcela_form,
        }
        return render(request, template_name_createreceita, context)


class ReceitaList(LoginRequiredMixin, ListView):
    model = Receita
    template_name = "receita/receitaList.html"


receitaList = ReceitaList.as_view()


class ReceitaDetails(LoginRequiredMixin, DetailView):
    model = Receita
    template_name = "receita/receitaDetails.html"


receitaDetails = ReceitaDetails.as_view()


class ReceitaDelete(LoginRequiredMixin, DeleteView):
    model = Receita
    template_name = "receita/receitaDelete.html"
    success_url = success_url_receita


receitaDelete = ReceitaDelete.as_view()

project/receita/templates/receita/receitaCreateUpdate.html
{% extends 'index.html' %}

{% load static %}

<title> {% block title %} Receita {% endblock title%} </title>

{% block index %}
<div class="container">
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="card">
            <div class="card-header">
                <label class="fs-5 fw-bold">{{ titulo }}</label>
            </div>
            <div class="card-body label parcela-forms">
                <div class="row mb-2">
                    <div class="col-12 col-md-5">
                        <label for="id_cliente" class="">Cliente</label>
                        {{ form.cliente }}
                    </div>
                    <div class="col-6 col-md-2">
                        <label for="id_categoria1" class="">Categoria</label>
                        {{ form.categoria1 }}
                    </div>
                    <div class="col-6 col-md-2">
                        <label for="id_categoria2" class="">Categoria</label>
                        {{ form.categoria2 }}
                    </div>
                    <div class="col-6 col-md-1">
                        <label for="id_num_parcelas" class="">Parcelas</label>
                        {{ form.num_parcelas }}
                    </div>
                    <div class="col-6 col-md-2">
                        <label for="id_total" class="">Total</label>
                        {{ form.total }}
                    </div>
                    <div class="col-12 col-md-6">
                        <label for="id_nome" class="">Nome da Receita</label>
                        {{ form.nome }}
                    </div>
                    <div class="col-12 col-md-6">
                        <label for="id_descricao" class="">Descricao</label>
                        {{ form.descricao }}
                    </div>
                </div>
            </div>
        </div>
        {% if parcela %}
        {{ parcela.management_form }}
        {{ parcela.non_form_errors }}
        <div class="card mt-2">
            <div class="card-header"><label class="fs-5 fw-bold">Parcelas</label></div>
            <div class="card-body label pt-0" id="parcela-form-list">
                {% for parc in parcela %}
                <div class="row parcela-form mt-2">
                    {{ parc.id }}
                    {{ parc.receita }}
                    {{ parc.datadocumento }}
                    <div class="col-6 col-lg-2">
                        {{ parc.valor.label_tag }}
                        {{ parc.valor.errors }}
                        {{ parc.valor }}
                    </div>
                    <div class="col-6 col-lg-2">
                        {{ parc.datavencimento.label_tag }}
                        {{ parc.datavencimento.errors }}
                        {{ parc.datavencimento }}
                    </div>
                    <div class="col-6 col-lg-2">
                        {{ parc.formapgto.label_tag }}
                        {{ parc.formapgto.errors }}
                        {{ parc.formapgto }}
                    </div>
                    {% if 'financeiro.change_contapagar' in perms %}
                    <div class="col-6 col-lg-2">
                        {{ parc.datapagamento.label_tag }}
                        {{ parc.datapagamento.errors }}
                        {{ parc.datapagamento }}
                    </div>
                    <div class="col-6 col-lg-2">
                        {{ parc.valor_pago.label_tag }}
                        {{ parc.valor_pago }}
                    </div>
                    <div class="col-12 col-lg-4">
                        {{ parc.detalhes.label_tag }}
                        {{ parc.detalhes.errors }}
                        {{ parc.detalhes }}
                    </div>
                    <div class="col-12 col-lg-6">
                        {{ parc.boleto.label_tag }}
                        {{ parc.boleto.errors }}
                        {{ parc.boleto }}
                    </div>
                    <div class="col-12 col-lg-6">
                        {{ parc.comprovante.label_tag }}
                        {{ parc.comprovante.errors }}
                        {{ parc.comprovante }}
                    </div>
                    {% else %}
                    <div class="col-12 col-lg-6">
                        {{ parc.detalhes.label_tag }}
                        {{ parc.detalhes.errors }}
                        {{ parc.detalhes }}
                    </div>
                    <div class="col-12 col-lg-6">
                        {{ parc.boleto.label_tag }}
                        {{ parc.boleto.errors }}
                        {{ parc.boleto }}
                    </div>
                    {% endif %}
                    <!-- <div class="col-6 col-lg-1 d-flex align-items-center">
                        <label class="pe-2" for="">Apagar </label>
                        {{ parc.DELETE}}
                    </div> -->
                </div>
                <hr class="mt-2 mb-0">
                {% endfor %}
            </div>
            <div id='empty-parcela' class="hidden">
                {{ parcela.empty_form.id }}
                {{ parcela.empty_form.receita }}
                {{ parcela.empty_form.datadocumento }}
                <div class="col-6 col-lg-2">
                    {{ parcela.empty_form.valor.label_tag }}
                    {{ parcela.empty_form.valor.errors }}
                    {{ parcela.empty_form.valor }}
                </div>
                <div class="col-6 col-lg-2">
                    {{ parcela.empty_form.datavencimento.label_tag }}
                    {{ parcela.empty_form.datavencimento.errors }}
                    {{ parcela.empty_form.datavencimento }}
                </div>
                <div class="col-6 col-lg-2">
                    {{ parcela.empty_form.formapgto.label_tag }}
                    {{ parcela.empty_form.formapgto.errors }}
                    {{ parcela.empty_form.formapgto }}
                </div>
                {% if 'financeiro.change_contapagar' in perms %}
                <div class="col-6 col-lg-2">
                    {{ parcela.empty_form.datapagamento.label_tag }}
                    {{ parcela.empty_form.datapagamento.errors }}
                    {{ parcela.empty_form.datapagamento }}
                </div>
                <div class="col-6 col-lg-2">
                    {{ parcela.empty_form.valor_pago.label_tag }}
                    {{ parcela.empty_form.valor_pago }}
                </div>
                <div class="col-12 col-lg-4">
                    {{ parcela.empty_form.detalhes.label_tag }}
                    {{ parcela.empty_form.detalhes.errors }}
                    {{ parcela.empty_form.detalhes }}
                </div>
                <div class="col-12 col-lg-6">
                    {{ parcela.empty_form.boleto.label_tag }}
                    {{ parcela.empty_form.boleto.errors }}
                    {{ parcela.empty_form.boleto }}
                </div>
                <div class="col-12 col-lg-6">
                    {{ parcela.empty_form.comprovante.label_tag }}
                    {{ parcela.empty_form.comprovante.errors }}
                    {{ parcela.empty_form.comprovante }}
                </div>
                {% else %}
                <div class="col-12 col-lg-6">
                    {{ parcela.empty_form.detalhes.label_tag }}
                    {{ parcela.empty_form.detalhes.errors }}
                    {{ parcela.empty_form.detalhes }}
                </div>
                <div class="col-12 col-lg-6">
                    {{ parcela.empty_form.boleto.label_tag }}
                    {{ parcela.empty_form.boleto.errors }}
                    {{ parcela.empty_form.boleto }}
                </div>
                {% endif %}
                <!-- <div class="col-6 col-lg-1 d-flex align-items-center">
                    <label class="pe-2" for="">Apagar </label>
                    {{ parcela.DELETE}}
                </div> -->
                <hr class="mt-2 mb-0">
            </div>
            <div class="m-2 btnMaster px-2"><button id="add-parcela" class="btnMaster btn btn-sm"
                    type="button">Adicionar nova parcela</button><i class="fa fa-plus-square" aria-hidden="true"></i>
            </div>
        </div>
        {% endif %}

        <div class="d-flex float-end m-3">
            <div class="col-3 d-flex gap-2 align-middle">
                <a role="button" class="btn btn-secondary btn-sm" href="{% url 'receita:receitaList' %}">Cancelar</a>
                <div class="form-group form-button">
                    <input type="submit" class="btn btn-primary btn-sm" value="Salvar" />
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

{% block script %}
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/select2.min.js' %}"></script>
<script>
    // select2 fornecedor
    $(document).ready(function () {
        $('#id_cliente').select2();
    });

    // adiciona nova parcela
    const addParcelaBtn = document.getElementById('add-parcela')
    const totalPacelasForms = document.getElementById('id_contareceber_set-TOTAL_FORMS')

    const num_parcelas = document.getElementById('id_num_parcelas');
    num_parcelas.setAttribute('value', totalPacelasForms.value);

    addParcelaBtn.addEventListener('click', add_new_parcela_form)
    function add_new_parcela_form(event) {
        if (event) {
            event.preventDefault();
        }
        const currentParcelaForms = document.getElementsByClassName("parcela-form");
        const currentParcelaFormCount = currentParcelaForms.length;
        const formParcelaCopyTarget = document.getElementById("parcela-form-list");
        const copyParcelaEmptyFormEl = document.getElementById('empty-parcela').cloneNode(true);
        copyParcelaEmptyFormEl.setAttribute('class', 'row parcela-form');
        copyParcelaEmptyFormEl.setAttribute('id', `contareceber_set-${currentParcelaFormCount}`);
        const regexParcela = new RegExp('__prefix__', 'g');
        copyParcelaEmptyFormEl.innerHTML = copyParcelaEmptyFormEl.innerHTML.replace(regexParcela, currentParcelaFormCount);
        totalPacelasForms.setAttribute('value', currentParcelaFormCount + 1);
        formParcelaCopyTarget.append(copyParcelaEmptyFormEl);
        num_parcelas.setAttribute('value', totalPacelasForms.value);
    }


    var total = document.getElementById('id_total');

    // soma o valor das parcelas
    function somaTotal() {
        let sum = 0;
        for (let i = 0; i < num_parcelas.value; i++) {
            var preco = $(`#id_contareceber_set-${i}-valor`).val();
            sum += Number(preco)
        }
        total.setAttribute('value', sum.toFixed(2));
    }

</script>
{% endblock %}

project/receita/templates/receita/receitaDelete.html
{% extends 'index.html' %}

{% load static %}

<title> {% block title %} Delete Receita {% endblock title%} </title>


{% block index %}
<main class="py-4">
    <div class="container">
        <h5>Delete</h5>
        <div class="cols-6">
            <form action="." method="POST">
                <div class="col-sm-6">
                    {% csrf_token %}
                    <p>Você tem certeza que deseja deletar o registro: <b>{{ object }}</b>?</p>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-sm">Confirmar</button>
                        <a class="btn btn-secondary btn-sm" href="{% url 'receita:receitaList' %}">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock %}

project/receita/templates/receita/receitaList.html
{% extends 'index.html' %}

{% load static %}

<title> {% block title %} Receitas {% endblock title%} </title>


{% block index %}

<div class="container">
    <div class="filters card border-1">
        <div class="card-header">
            <label class="fs-5 fw-bold">Receitas</label>
        </div>
        <div class="table-responsive p-3">
            <table class="table table-sm" id="id_table">
                <div class="col-12 d-flex justify-content-end">
                    <a class="btnMaster px-2" href="{% url 'receita:receitaCreate' %}">Nova Receita
                        <i class="fa fa-plus-square" aria-hidden="true"></i>
                    </a>
                </div>
                <thead>
                    <tr>
                        <th>Data</th>
                        <th>Receita</th>
                        <th>Total</th>
                        <th>Categoria1</th>
                        <th>Categoria2</th>
                        <th>Parcelas</th>
                        <th>Descrição</th>
                        <th>Cliente</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in object_list %}
                    <tr>
                        <td>{{ obj.criadoem|date:"y-m-d" }}</td>
                        <td>{{ obj.nome }}</td>
                        <td>R$ {{ obj.total|floatformat:2 }}</td>
                        <td>{{ obj.categoria1 }}</td>
                        <td>{{ obj.categoria2 }}</td>
                        <td class="text-center">{{ obj.num_parcelas }}</td>
                        <td>{{ obj.descricao }}</td>
                        <td>{{ obj.cliente|default:""|truncatechars:30 }}</td>
                        <td>
                            <a class="px-1" href="{{ obj.receita_gau_edit }}">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a class="px-1" href="{{ obj.receita_gau_delete }}" style="padding-left: 7px">
                                <i class="fa fa-close no"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script src="{% static 'js/datatables.min.js' %}"></script>
<script src="{% static 'js/jqueryDataTable.js' %}"></script>

<script>
    $(document).ready(function () {
        $('#id_table').DataTable({
            "columnDefs": [
                {
                    "targets": 0, // Supondo que a coluna de data seja a primeira
                    "render": function (data, type, row, meta) {
                        if (type === 'display') {
                            var dateSplit = data.split('-');
                            return dateSplit[2] + '/' + dateSplit[1] + '/' + dateSplit[0]; // Formato DD/MM/YYYY
                        }
                        return data; // Para sort e outros tipos, retornar data sem modificação
                    }
                }
            ],
            "order": [0, 'desc'],
            "pageLength": 100,
            "language": {
                "sProcessing": "Proccesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "Nenhum resultado encontrado",
                "sEmptyTable": "Nenhum dado disponivel",
                "sInfo": "Mostrando registros de _START_ a _END_ de um total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros de 0 a 0 de um total de 0 registros",
                "sInfoFiltered": "(filtrado de um total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Carregando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Seguinte",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Ativar para ordenar a coluna de maneira ascendente",
                    "sSortDescending": ": Ativar para ordenar a coluna de maneira descendente"
                }
            }
        });
    }); 
</script>
{% endblock %}